module.exports = [
  "Format input stok:",
  "input#nama motor;tahun;plat;surat-surat;tahun plat;pajak;harga jual;harga laku;harga beli;tgl terjual;status",
  "",
  "Format label (lebih mudah):",
  "NAMA MOTOR: Vario 125",
  "TAHUN: 2022",
  "PLAT: B1234XYZ",
  "SURAT-SURAT: Lengkap hidup",
  "TAHUN PLAT: 2027",
  "PAJAK: Hidup",
  "HARGA JUAL: 22500000",
  "HARGA BELI: 19000000",
  "",
  "Format update label:",
  "NO: 7",
  "HARGA JUAL: 22500000",
  "HARGA LAKU: 21000000",
  "TGL TERJUAL: 24/02/2026",
  "STATUS: terjual",
  "",
  "Format input singkat (stok awal):",
  "input#nama motor;tahun;plat;surat-surat;tahun plat;pajak;harga jual;harga beli",
  "",
  "Format update saat terjual:",
  "update#no;harga jual;harga laku;tgl terjual;status",
  "",
  "Format cek data motor:",
  "data motor vixion",
  "cek data motor vixion",
  "",
  "Template motor masuk (2 tahap):",
  "motor masuk",
  "isi template lalu ketik OK untuk simpan / BATAL untuk batal",
  "",
  "Contoh:",
  "input#Vario 125;2022;B1234XYZ;Lengkap hidup;2027;Hidup;22500000;19000000",
  "update#7;22500000;21000000;24/02/2026;terjual",
  "",
  "Catatan:",
  "- input stok boleh kosong di field manapun, data tetap tersimpan",
  "- disarankan minimal isi NAMA MOTOR/PLAT agar mudah dicari",
  "- surat-surat hanya: Lengkap hidup / Lengkap mati / BPKB ONLY",
  "- PAJAK boleh kirim tahun (contoh 2027) atau status Hidup/Mati",
  "- update pakai NO (kolom A), bukan PLAT",
  "- jika update HARGA LAKU tanpa TGL TERJUAL, tanggal otomatis hari ini",
  "- tgl terjual dan status boleh dikosongkan",
  "- status otomatis centang jika harga laku / tgl terjual terisi",
  "- status manual: terjual/ya/1 = dicentang"
].join("\n");
