const INTENTS = {
  INPUT_DATA: "INPUT_DATA",
  EDIT_DATA: "EDIT_DATA",
  VIEW_DATA: "VIEW_DATA",
  DELETE_DATA: "DELETE_DATA",
  CONFIRM_SOLD: "CONFIRM_SOLD",
  ASSISTANT: "ASSISTANT"
};

const DATA_INTENTS = new Set([
  INTENTS.INPUT_DATA,
  INTENTS.EDIT_DATA,
  INTENTS.VIEW_DATA,
  INTENTS.DELETE_DATA,
  INTENTS.CONFIRM_SOLD
]);

const TARGET_SHEETS = {
  STOK_MOTOR: "STOK_MOTOR",
  PENGELUARAN_HARIAN: "PENGELUARAN_HARIAN",
  TOTAL_ASET: "TOTAL_ASET"
};

module.exports = {
  INTENTS,
  DATA_INTENTS,
  TARGET_SHEETS
};
